#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Wed Apr 08 15:28:09 CLT 2026
#Wed Apr 08 15:28:09 CLT 2026
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ (\ deltatime\ <\ 1000.0\ )\ )\ ?\ ((\ (\ tsFuelFlowGph\ *\ deltatime\ /\ 3600.0\ )\ ))\ \:\ (0.0)=0.0
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=0.0
