#Persisted Channels storage file  by EFI Analytics, Inc
#Last Saved on: Sat Apr 04 11:23:43 CLST 2026
#Sat Apr 04 11:23:43 CLST 2026
_(\ (\ deltatime\ <\ 1000.0\ )\ )\ ?\ ((\ (\ tsFuelFlowGph\ *\ deltatime\ /\ 3600.0\ )\ ))\ \:\ (0.0)=0.0
_(\ (\ tsInputSpeedMPH\ *\ 1.60934\ )\ /\ 3600.0\ *\ deltatime\ )=0.0
_(\ tsInputSpeedMPH\ /\ 3600.0\ *\ deltatime\ )=0.0
