#Project Attributes.
#TunerStudio by EFI Analytics, Inc
#Last Saved on: Wed Apr 08 09:31:17 CLT 2026
#Wed Apr 08 09:31:17 CLT 2026
boostctlSettingsBoost\ Control\ Settings_width=808
pwmidle_cl_initialvaluesClosed-Loop\ Idle\ Initial\ Values_height=439
nestedasePctAfterStart\ Enrichment\ (ASE)_Y=53
CommSettingDESKTOP-18VBRI9CommDriver.RS232\ Serial\ InterfaceCom\ Port=COM1
egoControlEGO\ Control_width=391
nestedasePctAfterStart\ Enrichment\ (ASE)_X=251
Triggers.ActiveTriggers=syncLossDetect|cltTempWarning|
AEtime_settingsTime-Based\ Accel\ Enrichment_Y=6
AEtime_settingsTime-Based\ Accel\ Enrichment_X=109
generalsettings2General\ Settings_height=616
ignitionTbl3Ignition\ Table\ 3\ (Spark\ Advance)_height=538
pwmidle_target_curve_Auto\ Scale\ X\ Axis\ Maximum=true
ShiftSettingsSequential\ Shift\ Cut_Y=180
ShiftSettingsSequential\ Shift\ Cut_X=511
ignitionTbl1Ignition\ Table\ 1\ (Spark\ Advance)_width=632
egoControlEGO\ Control_height=551
warmup_curve_Set\ X\ Axis\ Minimum=-40.0
CommSettingDESKTOP-18VBRI9CommDriver.controllerInterfaceId=Bluetooth Direct
idlebinsIdle\ Warmup\ Duty/Steps_height=525
nestedwarmup_curveWarmup\ Enrichment\ (WUE)_height=506
veGenerator_txtPkTqMap=100
veGenerator_cBoost=Naturally Aspirated
userDash0.DashName=Main
stagedCombinedStaged\ Injection_height=511
tuneFileDir=C\:\\Users\\Setterleee\\OneDrive\\TunerStudioProjects\\4G15 NA v2\\restorePoints
VeAnalyzeConsole.veTable1Tbl_horizontalSplitPos=201
dwellSettingsDwell\ Battery\ Correction_Y=200
dwellSettingsDwell\ Battery\ Correction_X=212
pwmidle_crank_dutyorsteps_dutycurve_showText=true
idle_voltage_comp_curvePWM\ Idle\ Voltage\ Compensation_width=460
veTable3TblFuel\ VE\ Table\ 3_Y=64
veTable3TblFuel\ VE\ Table\ 3_X=626
asePct_Auto\ Scale\ Y\ Axis\ Maximum=true
matclt_curveMAT/CLT\ Correction_Y=201
matclt_curveMAT/CLT\ Correction_X=496
AEtime_settingsTime-Based\ Accel\ Enrichment_height=695
nestedasePctAfterStart\ Enrichment\ (ASE)_height=530
outputtest_ioOutput\ Test\ Mode\ -\ I/O_height=477
N2OSystemNitrous\ System_Y=114
N2OSystemNitrous\ System_X=491
time_accel_tpsdot_curve_Auto\ Scale\ X\ Axis\ Maximum=true
iactestOutput\ Test\ Mode\ -\ Idle\ Valve_height=407
wueAfrTargetOffsetCurve_Set\ X\ Axis\ Minimum=-40.0
pwmidle_cl_initialvaluesClosed-Loop\ Idle\ Initial\ Values_Y=178
pwmidle_cl_initialvaluesClosed-Loop\ Idle\ Initial\ Values_X=584
projectName=4G15 NA v2
selectedComDriver=Multi Interface MegaSquirt Driver
Triggers.base.ActiveTriggers=
crankingPW_showText=true
primingPWPriming\ Pulse_width=717
ignitionTbl3Ignition\ Table\ 3\ (Spark\ Advance)_width=726
crankingPWCranking\ Pulse\ %_Y=101
overrunOver-Run\ Fuel\ Cut_Y=175
injpw_menuFuel\ Metering\ Pulse_Y=259
crankingPWCranking\ Pulse\ %_X=192
veGenerator_txtDisplacementCid=90
overrunOver-Run\ Fuel\ Cut_X=502
injpw_menuFuel\ Metering\ Pulse_X=519
knockSettingsKnock\ Sensor\ Settings_width=1040
combinedCLidleClosed-Loop\ Idle\ Settings_height=531
outputtest_ioOutput\ Test\ Mode\ -\ I/O_width=854
time_accel_tpsdot_curve_showText=true
coldAdvanceCold\ Advance_Y=104
coldAdvanceCold\ Advance_X=150
CommSettingMSCommDriver.RS232\ Serial\ InterfaceBluetooth\ Port=false
idlebinsIdle\ Warmup\ Duty/Steps_width=691
dashbcastDash\ Broadcasting_Y=235
dashbcastDash\ Broadcasting_X=522
injseqSequenced\ Batch\ Fire_height=231
accelsettingsAccel\ Enrich\ Settings_Y=444
accelsettingsAccel\ Enrich\ Settings_X=678
idleAdvanceIdle\ Advance\ Settings_Y=183
veGenerator_txtPkTqRpm=3000
idleAdvanceIdle\ Advance\ Settings_X=512
tableswTable\ Switching\ Control_height=421
2DTable_ignitionTbl3_tableInitialDir=C\:\\Users\\Setterleee\\OneDrive\\TunerStudioProjects\\4G15 NA v2
veTable1TblFuel\ VE\ Table\ 1_Y=154
veTable1TblFuel\ VE\ Table\ 1_X=348
sensorCalCalibrate\ MAP/Baro_width=319
userDash2.DashName=Acceleration Performance
outputtest_ioOutput\ Test\ Mode\ -\ I/O_Y=191
outputtest_ioOutput\ Test\ Mode\ -\ I/O_X=547
battcalibCalibrate\ Battery\ Voltage_height=207
VeAnalyzeConsole.veTable1Tbl_verticalSplitPos=513
matclt_curveMAT/CLT\ Correction_height=326
map_sample_dialogMAP\ Sample\ Settings_height=241
injCharsInjector\ Dead-Time/PWM_height=399
commPort=COM1
knockSettingsKnock\ Sensor\ Settings_Y=85
knockSettingsKnock\ Sensor\ Settings_X=163
idlebinsIdle\ Warmup\ Duty/Steps_Y=77
map_sample_dialogMAP\ Sample\ Settings_width=320
idlebinsIdle\ Warmup\ Duty/Steps_X=571
coldAdvanceCold\ Advance_width=726
userDash1.FileName=Tablet.dash
pwmidle_crank_dutyorsteps_curveIdle\ Cranking\ Duty/Steps_height=611
revlimiter2Rev\ Limiter_Y=86
revlimiter2Rev\ Limiter_X=198
outputtestOutput\ Test\ Mode\ -\ Inj/Spk_width=670
pwmidle_crank_dutyorsteps_dutycurve_Auto\ Scale\ X\ Axis\ Maximum=true
AEtime_settingsTime-Based\ Accel\ Enrichment_width=1119
useCommonDashboardDir=false
egoControlEGO\ Control_Y=51
egoControlEGO\ Control_X=292
CommSettingMSCommDriver.RS232\ Serial\ InterfaceCom\ Port=COM1
combinedignitionIgnition\ Options\ /\ Wheel\ Decoder_Y=73
combinedignitionIgnition\ Options\ /\ Wheel\ Decoder_X=275
ac_idleupAir\ Conditioning\ Idle-up_Y=168
ac_idleupAir\ Conditioning\ Idle-up_X=512
crsettingsCranking\ /\ Startup\ settings_width=394
warmup_curve_Auto\ Scale\ X\ Axis\ Maximum=true
idle_voltage_comp_curvePWM\ Idle\ Voltage\ Compensation_Y=201
idle_voltage_comp_curvePWM\ Idle\ Voltage\ Compensation_X=496
std_port_editProgrammable\ On/Off\ Outputs_Y=188
std_port_editProgrammable\ On/Off\ Outputs_X=690
injCharsInjector\ Dead-Time/PWM_Y=225
pwmidle_crank_dutyorsteps_stepscurve_Set\ X\ Axis\ Minimum=-40.0
injCharsInjector\ Dead-Time/PWM_X=655
CommSettingDESKTOP-18VBRI9CommDriver.FTDI\ -\ D2XX\ driverDevice\ Serial\ \#=Auto
pwmidle_crank_dutyorsteps_curveIdle\ Cranking\ Duty/Steps_width=732
mafdialogMAF\ Settings_width=479
stagedCombinedStaged\ Injection_Y=108
stagedCombinedStaged\ Injection_X=363
idleAdvance_rpm_curve_showText=true
baseEngine\ and\ Sequential\ Settings_width=714
revlimiter2Rev\ Limiter_width=970
idleAdvance_rpm_curveIdle\ RPM\ Advance\ Timing_height=500
afrTable1Map3DAFR\ Table\ 1_height=541
sparkcalcsSpark\ Calculations\ Summary_width=675
baudRate=115200
fuelcalcsFuel\ Calculations\ Summary_Y=0
flexFuelSettingsFuel\ Sensor\ Settings\ (Flex)_Y=163
nestedasePctAfterStart\ Enrichment\ (ASE)_width=739
fuelcalcsFuel\ Calculations\ Summary_X=265
flexFuelSettingsFuel\ Sensor\ Settings\ (Flex)_X=460
combinedCLidleClosed-Loop\ Idle\ Settings_Y=105
combinedCLidleClosed-Loop\ Idle\ Settings_X=540
iactestOutput\ Test\ Mode\ -\ Idle\ Valve_width=613
combinedignitionIgnition\ Options\ /\ Wheel\ Decoder_height=641
lastDisplayedTuneFile=Modified - 4G15 NA v2_2026-03-21_16.55.33.msq
VeAnalyzeConsole.veTable1Tbl_selectedDash=Standard
nestedasePctAfterStart\ Enrichment\ (ASE)\ -\ Percent\ Adder_width=761
iopinlistFeature\ list\ Showing\ I/O\ Pins_height=738
crankingPW_Auto\ Scale\ Y\ Axis\ Maximum=true
noisefiltering2Noise\ Filtering_width=651
aseTaperAfterStart\ Enrichment\ (ASE)\ Taper_height=486
fuelcalcsFuel\ Calculations\ Summary_width=835
canparamsCAN\ Parameters_width=741
std_port_editProgrammable\ On/Off\ Outputs_height=357
crsettingsCranking\ /\ Startup\ Settings_Y=247
crsettingsCranking\ /\ Startup\ Settings_X=516
time_accel_mapdot_curve_Auto\ Scale\ X\ Axis\ Maximum=true
asePct_Auto\ Scale\ X\ Axis\ Maximum=true
2DTable_veTable1Tbl_tableInitialDir=C\:\\Users\\Setterleee\\Desktop
WueAnalyzeConsole.wueAnalyzer_warmup_curve_selectedDash=Standard
fuelcalcsFuel\ Calculations\ Summary_height=738
CommSettingDESKTOP-18VBRI9CommDriver.RS232\ Serial\ InterfaceBaud\ Rate=115200
pwmidle_target_curve_showText=true
veGenerator_txtIdleMap=23
pwmidle_crank_dutyorsteps_curveIdle\ Cranking\ Duty/Steps_Y=38
tachoTacho\ Output_width=329
pwmidle_crank_dutyorsteps_curveIdle\ Cranking\ Duty/Steps_X=540
barometerCorrBarometric\ Correction_width=678
nestedasePctAfterStart\ Enrichment\ (ASE)\ -\ Percent\ Adder_height=530
combinedCLidleClosed-Loop\ Idle\ Settings_width=763
idle_voltage_comp_curvePWM\ Idle\ Voltage\ Compensation_height=393
veTable1TblFuel\ VE\ Table\ 1_height=472
projectDescription=4g15 v2 Naturraly Aspired
CommSettingCom\ Port=COM1
combinedidleIdle\ Control_height=424
baseEngine\ and\ Sequential\ Settings_height=532
CommSettingBaud\ Rate=115200
2DTable_afrTable1Tbl_tableInitialDir=C\:\\Users\\Setterleee\\OneDrive\\Documentos\\TunerStudioProjects\\4G15 NA v2 (To Edit in Mac)\\Tables
battcalibCalibrate\ Battery\ Voltage_width=343
veGenerator_txtPkHp=94
matBasedRetard_Set\ X\ Axis\ Minimum=-40.0
accelsettingsAccel\ Enrich\ Settings_width=359
combinedignitionIgnition\ Options\ /\ Wheel\ Decoder_width=751
logFileDir=C\:\\Users\\Setterleee\\OneDrive\\TunerStudioProjects\\4G15 NA v2\\DataLogs
veGenerator_txtDisplacementCc=1468
ipwBins_Set\ X\ Axis\ Minimum=-40.0
combinedidleIdle\ Control_Y=145
combinedidleIdle\ Control_X=555
veTable1Map3DFuel\ VE\ Table\ 1_height=541
CommSettingMSCommDriver.FTDI\ -\ D2XX\ driverDevice\ Serial\ \#=Auto
idleAdvance_rpm_curve_Auto\ Scale\ X\ Axis\ Maximum=true
overrunOver-Run\ Fuel\ Cut_width=362
crsettingsCranking\ /\ Startup\ Settings_height=277
idleAdvance_rpm_curveIdle\ RPM\ Advance\ Timing_width=625
logTuningPanel_selectionTable2=veTable1Tbl
generalsettings2General\ Settings_Y=67
logTuningPanel_selectionTable1=ignitionTbl1
generalsettings2General\ Settings_X=36
overrunOver-Run\ Fuel\ Cut_height=341
noisefiltering2Noise\ Filtering_height=471
dashbcastDash\ Broadcasting_width=322
N2OSystemNitrous\ System_width=383
WueAnalyzeConsole.wueAnalyzer_warmup_curve_verticalSplitPos=503
ac_idleupAir\ Conditioning\ Idle-up_height=355
crankingPWCranking\ Pulse\ %_width=920
veGenerator_txtIdleRpm=900
idleAdvanceIdle\ Advance\ Settings_height=327
flexFuelSettingsFuel\ Sensor\ Settings\ (Flex)_width=448
CommSettingMSCommDriver.FTDI\ -\ D2XX\ driverBaud\ Rate=115200
manifoldTempCorr2MAT\ Air\ Density\ Table_width=853
launchLaunch\ Control_height=407
firmwareDescription=MS2/Extra 3.4.4 release  20201006 18\:17BST(c)KC/JSM/JB   uSM
canparamsCAN\ Parameters_height=426
knockSettingsKnock\ Sensor\ Settings_height=557
dwellSettingsDwell\ Battery\ Correction_height=408
injseqSequenced\ Batch\ Fire_Y=230
CommSettingDESKTOP-18VBRI9CommDriver.RS232\ Serial\ InterfaceBluetooth\ Port=false
injseqSequenced\ Batch\ Fire_X=490
sparkcalcsSpark\ Calculations\ Summary_height=738
launchLaunch\ Control_Y=181
dashbcastDash\ Broadcasting_height=257
launchLaunch\ Control_X=668
injCharsInjector\ Dead-Time/PWM_width=332
refTable_002_txtY2=18
refTable_002_txtY1=8.5
CommSettingMSCommDriver.controllerInterfaceId=Bluetooth Direct
warmup_curve_Show\ baseline\ graph\ (CTRL+B)=true
map_sample_dialogMAP\ Sample\ Settings_Y=225
map_sample_dialogMAP\ Sample\ Settings_X=532
warmup_curve_showText=true
crankingPW_Set\ X\ Axis\ Minimum=-40.0
veTable3TblFuel\ VE\ Table\ 3_width=695
nestedwarmup_curveWarmup\ Enrichment\ (WUE)\ -\ Percent\ Multiplier_Y=54
nestedwarmup_curveWarmup\ Enrichment\ (WUE)\ -\ Percent\ Multiplier_X=76
crsettingsCranking\ /\ Startup\ settings_Y=225
crsettingsCranking\ /\ Startup\ settings_X=486
refTable_002_txtX2=4.5
refTable_002_txtX1=0.50
tsSupplementalFieldsVehicle\ Specifications_Y=144
tsSupplementalFieldsVehicle\ Specifications_X=310
coldAdvanceCold\ Advance_height=486
tachoTacho\ Output_Y=237
tachoTacho\ Output_X=527
boostctlSettingsBoost\ Control\ Settings_height=581
veTable1Map3DFuel\ VE\ Table\ 1_Y=93
accelsettingsAccel\ Enrich\ Settings_height=175
veTable1Map3DFuel\ VE\ Table\ 1_X=275
userDash1.DashName=Tablet
outputtestOutput\ Test\ Mode\ -\ Inj/Spk_Y=11
useCommonTuneViewDir=false
outputtestOutput\ Test\ Mode\ -\ Inj/Spk_X=520
pwmidle_target_curveClosed-Loop\ Idle\ Target\ RPMs_Y=170
pwmidle_target_curveClosed-Loop\ Idle\ Target\ RPMs_X=645
battcalibCalibrate\ Battery\ Voltage_Y=260
pwmidle_crank_dutyorsteps_dutycurve_Auto\ Scale\ Y\ Axis\ Maximum=true
battcalibCalibrate\ Battery\ Voltage_X=511
matBasedRetardMAT-Based\ Timing\ Retard_Y=134
userDash0.FileName=Main.dash
matBasedRetardMAT-Based\ Timing\ Retard_X=416
revlimiterBins_Set\ X\ Axis\ Minimum=-40.0
tachoTacho\ Output_height=217
barometerCorrBarometric\ Correction_height=433
warmup_curve_Auto\ Scale\ Y\ Axis\ Maximum=true
noisefiltering2Noise\ Filtering_Y=128
noisefiltering2Noise\ Filtering_X=357
outputtestOutput\ Test\ Mode\ -\ Inj/Spk_height=703
ac_idleupAir\ Conditioning\ Idle-up_width=341
canId=0
baseEngine\ and\ Sequential\ Settings_Y=80
afrTable1Map3DAFR\ Table\ 1_width=816
baseEngine\ and\ Sequential\ Settings_X=339
pwmidle_target_curveClosed-Loop\ Idle\ Target\ RPMs_width=601
tsSupplementalFieldsVehicle\ Specifications_width=745
CommSettingDESKTOP-18VBRI9CommDriver.FTDI\ -\ D2XX\ driverBaud\ Rate=115200
ignitionTbl3Ignition\ Table\ 3\ (Spark\ Advance)_Y=167
ignitionTbl3Ignition\ Table\ 3\ (Spark\ Advance)_X=580
veTable1TblFuel\ VE\ Table\ 1_width=642
coldAdvance_Auto\ Scale\ Y\ Axis\ Maximum=true
veGenerator_txtPkHpMap=100
asePct_showText=true
iacBins_Set\ X\ Axis\ Minimum=-40.0
2DTable_ignitionTbl1_tableInitialDir=C\:\\Users\\Setterleee\\OneDrive\\Documentos\\Temp
aseTaper_Set\ X\ Axis\ Minimum=-40.0
ecuSettings=CAN_COMMANDS_OFF|CELSIUS|EGTFULL_OFF|EXPANDED_CLT_TEMP_OFF|OUTMSG_EDITING_OFF|PORT_STATUS_OFF|
aseTaperAfterStart\ Enrichment\ (ASE)\ Taper_width=726
limitsettingsGauge\ and\ Settings\ Limits_height=311
pwmidle_target_curve_Auto\ Scale\ Y\ Axis\ Maximum=true
launchLaunch\ Control_width=347
veGenerator_txtMaxRpm=6500
WueAnalyzePanel_wueAnalyzer_warmup_curve_applyPeriod=Manually
time_accel_mapdot_curve_showText=true
idle_voltage_comp_curve_showText=true
boostctlSettingsBoost\ Control\ Settings_Y=55
boostctlSettingsBoost\ Control\ Settings_X=279
aseTaperAfterStart\ Enrichment\ (ASE)\ Taper_Y=121
aseTaperAfterStart\ Enrichment\ (ASE)\ Taper_X=320
combinedidleIdle\ Control_width=661
veTable3TblFuel\ VE\ Table\ 3_height=454
afrTable1TblAFR\ Table\ 1_Y=66
afrTable1TblAFR\ Table\ 1_X=41
primingPWPriming\ Pulse_height=474
VeAnalyzeConsole.veTable3Tbl_selectedDash=Standard
time_accel_mapdot_curve_Auto\ Scale\ Y\ Axis\ Maximum=true
iopinlistFeature\ list\ Showing\ I/O\ Pins_Y=0
iopinlistFeature\ list\ Showing\ I/O\ Pins_X=410
userDash2.FileName=Acceleration_Performance.dash
stagedCombinedStaged\ Injection_width=640
mafdialogMAF\ Settings_height=265
iopinlistFeature\ list\ Showing\ I/O\ Pins_width=546
injpw_menuFuel\ Metering\ Pulse_height=173
primingPWPriming\ Pulse_Y=102
primingPWPriming\ Pulse_X=39
afrTable1TblAFR\ Table\ 1_height=658
ignitionTbl1Ignition\ Table\ 1\ (Spark\ Advance)_height=537
time_accel_tpsdot_curve_Auto\ Scale\ Y\ Axis\ Maximum=true
generalsettings2General\ Settings_width=708
asePct_Set\ X\ Axis\ Minimum=-40.0
ShiftSettingsSequential\ Shift\ Cut_height=367
manifoldTempCorr2MAT\ Air\ Density\ Table_Y=84
injseqSequenced\ Batch\ Fire_width=400
manifoldTempCorr2MAT\ Air\ Density\ Table_X=198
afrTable1TblAFR\ Table\ 1_width=1118
canparamsCAN\ Parameters_Y=151
sparkcalcsSpark\ Calculations\ Summary_Y=0
matclt_curveMAT/CLT\ Correction_width=374
canparamsCAN\ Parameters_X=312
sparkcalcsSpark\ Calculations\ Summary_X=345
sensorCalCalibrate\ MAP/Baro_height=375
veGenerator_txtPkHpRpm=6000
ecuUid=456bceeb-4d31-4234-9d56-847646e23358
primingPW_Set\ X\ Axis\ Minimum=-40.0
limitsettingsGauge\ and\ Settings\ Limits_Y=190
limitsettingsGauge\ and\ Settings\ Limits_X=499
afrTable1Map3DAFR\ Table\ 1_Y=93
afrTable1Map3DAFR\ Table\ 1_X=275
ShiftSettingsSequential\ Shift\ Cut_width=343
pwmidle_cl_initialvaluesClosed-Loop\ Idle\ Initial\ Values_width=702
crankingPWCranking\ Pulse\ %_height=506
2DTable_veTable3Tbl_tableInitialDir=C\:\\Users\\Setterleee\\OneDrive\\TunerStudioProjects\\4G15 NA v2
protocolEnvelope=
wueAnalyzer_warmup_curve_Set\ X\ Axis\ Minimum=-40.0
matBasedRetardMAT-Based\ Timing\ Retard_height=459
CommSettingMSCommDriver.Bluetooth\ DirectBluetooth\ Device=Megasquirt 2 (001212190030)
nestedwarmup_curveWarmup\ Enrichment\ (WUE)\ -\ Percent\ Multiplier_height=648
airdenCorr_Set\ X\ Axis\ Minimum=-40.0
sensorCalCalibrate\ MAP/Baro_Y=176
sensorCalCalibrate\ MAP/Baro_X=523
CommSettingDESKTOP-18VBRI9CommDriver.Bluetooth\ DirectBluetooth\ Device=Megasquirt 2 (001212190030)
pwmidle_target_curveClosed-Loop\ Idle\ Target\ RPMs_height=465
crsettingsCranking\ /\ Startup\ settings_height=277
idleAdvanceIdle\ Advance\ Settings_width=295
iactestOutput\ Test\ Mode\ -\ Idle\ Valve_Y=144
iactestOutput\ Test\ Mode\ -\ Idle\ Valve_X=695
CommSettingMSCommDriver.RS232\ Serial\ InterfaceBaud\ Rate=115200
manifoldTempCorr2MAT\ Air\ Density\ Table_height=575
crsettingsCranking\ /\ Startup\ Settings_width=394
idleAdvance_rpm_curve_Auto\ Scale\ Y\ Axis\ Maximum=true
VeAnalyzeConsole.veTable2Tbl_selectedDash=Standard
nestedwarmup_curveWarmup\ Enrichment\ (WUE)_width=772
limitsettingsGauge\ and\ Settings\ Limits_width=386
VeAnalyzeConsole.veTable3Tbl_verticalSplitPos=524
nestedasePctAfterStart\ Enrichment\ (ASE)\ -\ Percent\ Adder_Y=38
N2OSystemNitrous\ System_height=499
nestedasePctAfterStart\ Enrichment\ (ASE)\ -\ Percent\ Adder_X=100
nestedwarmup_curveWarmup\ Enrichment\ (WUE)_Y=51
nestedwarmup_curveWarmup\ Enrichment\ (WUE)_X=530
matBasedRetardMAT-Based\ Timing\ Retard_width=534
flexFuelSettingsFuel\ Sensor\ Settings\ (Flex)_height=365
coldAdvance_Set\ X\ Axis\ Minimum=-40.0
idleAdvance_rpm_curveIdle\ RPM\ Advance\ Timing_Y=156
idleAdvance_rpm_curveIdle\ RPM\ Advance\ Timing_X=255
crankingPW_Auto\ Scale\ X\ Axis\ Maximum=true
revlimiter2Rev\ Limiter_height=555
injpw_menuFuel\ Metering\ Pulse_width=328
tableswTable\ Switching\ Control_width=329
nestedwarmup_curveWarmup\ Enrichment\ (WUE)\ -\ Percent\ Multiplier_width=917
veGenerator_txtPkTq=93
mafdialogMAF\ Settings_Y=231
mafdialogMAF\ Settings_X=443
tableswTable\ Switching\ Control_Y=148
dashBoardFile=\\dashboard\\\\dashboard.dash
ecuConfigFile=mainController.ini
tableswTable\ Switching\ Control_X=636
tsSupplementalFieldsVehicle\ Specifications_height=439
pwmidle_crank_dutyorsteps_dutycurve_Set\ X\ Axis\ Minimum=-40.0
barometerCorrBarometric\ Correction_Y=147
veTable1Map3DFuel\ VE\ Table\ 1_width=816
ignitionTbl1Ignition\ Table\ 1\ (Spark\ Advance)_Y=137
std_port_editProgrammable\ On/Off\ Outputs_width=481
dwellSettingsDwell\ Battery\ Correction_width=790
barometerCorrBarometric\ Correction_X=344
ignitionTbl1Ignition\ Table\ 1\ (Spark\ Advance)_X=322
coldAdvance_Auto\ Scale\ X\ Axis\ Maximum=true
