#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Sat Apr 04 19:33:34 CLST 2026
converterStall=
injectorSize=550
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1499
