#Vehicles Attributes.
#TunerStudio by Philip Tobin
#Sat Feb 07 22:16:05 CLST 2026
converterStall=
injectorSize=184
firstGearRatio=
fourthGearRatio=
finalDriveRatio=
transmissionType=Manual
fifthGearRatio=
weight=
thirdGearRatio=
sixthGearRatio=
secondGearRatio=
engineDisplacement=1499
